// <auto-generated />
namespace ScrumProjekt.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Lagttilladminrattigheterpausers : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Lagttilladminrattigheterpausers));
        
        string IMigrationMetadata.Id
        {
            get { return "201901311037172_Lagt till adminrattigheter pa users"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
